# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2

xcode_project: Happa.xcodeproj
xcode_scheme: Happa
xcode_sdk: iphonesimulator

branches:
  only:
    - master
